# Generated by Django 5.0.6 on 2024-05-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Short",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("originalUrl", models.URLField(max_length=700)),
                ("shortUrl", models.CharField(max_length=100)),
                ("date_and_time", models.DateTimeField()),
            ],
        ),
    ]
